# Generated by Django 4.1.4 on 2022-12-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstancce',
            new_name='BookInstance',
        ),
    ]
