# Generated by Django 4.1.4 on 2022-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_bookinstancce_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Ведите язык оригинала', to='blog.language'),
        ),
    ]
