# Generated by Django 4.1.4 on 2022-12-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_book_options_remove_book_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gener',
            new_name='genre',
        ),
    ]
