# Generated by Django 4.1.4 on 2023-02-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bookinstance_borrower_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
